from __future__ import annotations

from pathlib import Path


DEFAULT_DB_PATH = Path(".indexes/novel.db")
DEFAULT_MEMORY_ROOT = Path(".memory")
DEFAULT_SEGMENTATION_STAGE = 'segmentation'
DEFAULT_CLOSE_READING_STAGE = 'close_reading'
DEFAULT_SEGMENT_CHUNK_MIN = 20000
DEFAULT_SEGMENT_CHUNK_MAX = 80000
DEFAULT_DOCUMENT_CHARS_MIN = 4096
DEFAULT_DOCUMENT_CHARS_MAX = 20480
DEFAULT_CLOSE_READ_DOC_BUDGET = 20000
DEFAULT_WORLD_SUMMARY_MAX_CHARS = 1024
DEFAULT_OUTLINE_MAX_CHARS = 10240
